apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helm-chart.fullname" . }}
  labels:
{{- include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "helm-chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          ports:
            - name: http
              containerPort: 8075
              protocol: TCP
          livenessProbe:
{{ toYaml .Values.livenessProbe| indent 12 }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
