apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
    {{- end }}
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
